package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.TLoginLog;
import test.model.TLoginLogExample;

public interface TLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int countByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int deleteByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer loginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int insert(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int insertSelective(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    List<TLoginLog> selectByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    TLoginLog selectByPrimaryKey(Integer loginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TLoginLog record, @Param("example") TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TLoginLog record, @Param("example") TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TLoginLog record);
}